<?php

    $v = file_get_contents( $argv[1] );
    $l = explode( "\n", $v ); // all lines in $l

    print ";No\$Zx symbolic information file\n";
    print ";Generated by makesym.php for fasmg/ez80 - By Stefano Maragò\n";
    print "\n";

/* ZX81 rom addresses
    print "00:02BB SCANKEYB \n";
    print "00:0F35 ROMPAUSE \n";
    print "00:0000 RESET    \n";
    print "00:0207 SLOWFAST \n";
    print "00:02E7 SETFAST  \n";
    print "00:0676 NEXTLINE \n";
    print "00:07bd DECODEKEY\n";
    print "00:08f5 PRINTAT  \n";
    print "00:099e MAKEROOM \n";
    print "00:0a2a CLS      \n";
    print "00:0bf5 STACK2BC \n";
    print "00:0c02 STACK2A  \n";
    print "00:0d92 CLASS6   \n";
    print "00:0ea7 FINDINT  \n";
    print "00:0f23 FAST     \n";
    print "00:0f2b SLOW     \n";
    print "00:0f4b DEBOUNCE \n";
    print "00:14BC SETMIN   \n";
    print "00:4001 FLAGS    \n";
    print "00:4000 ERR_NR   \n";
    print "00:4002 ERR_SP   \n";
    print "00:4004 RAMTOP   \n";
    print "00:4006 MODE     \n";
    print "00:4007 PPC      \n";
    print "00:4009 VERSN    \n";
    print "00:400A E_PPC    \n";
    print "00:400C D_File   \n";
    print "00:400E DF_CC    \n";
    print "00:4010 VARS     \n";
    print "00:4012 DEST     \n";
    print "00:4014 E_LINE   \n";
    print "00:4016 CH_ADD   \n";
    print "00:4018 X_PTR    \n";
    print "00:401A STKBOT   \n";
    print "00:401C STKEND   \n";
    print "00:401E BERG     \n";
    print "00:401F MEM      \n";
    print "00:4022 DF_SZ    \n";
    print "00:4023 S_TOP    \n";
    print "00:4025 LAST_K   \n";
    print "00:4027 DEBOUN   \n";
    print "00:4028 MARGIN   \n";
    print "00:4029 NXTLIN   \n";
    print "00:402B OLDPPC   \n";
    print "00:402D FLAGX    \n";
    print "00:402E STRLEN   \n";
    print "00:4030 T_ADDR   \n";
    print "00:4032 SEED     \n";
    print "00:4034 FRAMES   \n";
    print "00:4036 COORDS   \n";
    print "00:4038 PR_CC    \n";
    print "00:4039 S_POSN   \n";
    print "00:403B CDFLAG   \n";
    print "00:403C PRBUFF   \n";
    print "00:405D MEMBOT   \n";
*/

    for ( $i = 8; ; $i++ ) {
        if( $l[$i]=='' ) break;
        $a = substr( $l[$i] , 4, 4 );
        $b = trim( substr( $l[$i] , 34 ) );
        $c = explode( " ", $b );
        if( count($c)>2 and ( $c[1]=='db' or $c[1]=='dw' ) ) $b = $c[0] . ( substr($c[0],-1,1)==':'?:":" );
        if( substr( $b, -1, 1 )==":" ) {
            print "00:" . $a . " " . substr( $b, 0, strlen($b)-1 ) . "\n";
        }
    }
